# Generated by Django 5.1.6 on 2025-03-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projet',
            new_name='Project',
        ),
    ]
