# Generated by Django 5.1.6 on 2025-04-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='image',
            field=models.ImageField(null=True, upload_to='opinions', verbose_name='Illustration'),
        ),
    ]
