# Generated by Django 5.1.6 on 2025-04-01 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0003_experience_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='opinion_experience',
            new_name='experience',
        ),
    ]
