# Generated by Django 5.1.6 on 2025-04-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_rename_opinion_experience_opinion_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='is_priority',
            field=models.BooleanField(default=False, verbose_name='Afficher sur la page de garde'),
            preserve_default=False,
        ),
    ]
