# Generated by Django 5.1.6 on 2025-04-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0005_opinion_is_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='is_priority',
            new_name='is_priority_2',
        ),
    ]
