# Generated by Django 5.1.6 on 2025-04-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0006_rename_is_priority_opinion_is_priority_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='is_priority_2',
        ),
        migrations.AddField(
            model_name='experience',
            name='is_priority',
            field=models.BooleanField(default=True, verbose_name='Afficher sur la page de garde'),
            preserve_default=False,
        ),
    ]
