# Generated by Django 5.1.6 on 2025-04-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0007_remove_opinion_is_priority_2_experience_is_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Site web'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='opinions', verbose_name='Illustration'),
        ),
    ]
