# Generated by Django 5.1.6 on 2025-04-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0008_alter_experience_website_alter_opinion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='role',
            field=models.CharField(default='Employé', max_length=120, verbose_name='Fonction'),
        ),
    ]
