# Generated by Django 5.1.6 on 2025-03-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('date', models.DateField(verbose_name="Date d'obention")),
                ('description', models.TextField(help_text='Utilisez Markdown', verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certifications', verbose_name='Image')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
            },
        ),
    ]
