# Generated by Django 5.1.6 on 2025-03-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='duration',
            field=models.IntegerField(default=None, verbose_name='Durée'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certification',
            name='mastery',
            field=models.CharField(choices=[(1, 'Debutant'), (2, 'Intermediaire'), (3, 'Avance'), (4, 'Expert')], default='default', max_length=100, verbose_name='Maîtrise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certification',
            name='organism',
            field=models.CharField(default='default', max_length=100, verbose_name='Organisme'),
            preserve_default=False,
        ),
    ]
