# Generated by Django 5.1.6 on 2025-03-30 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0002_certification_duration_certification_mastery_and_more'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skills.language'),
        ),
    ]
