# Generated by Django 5.1.6 on 2025-03-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0003_certification_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='duration_measure',
            field=models.CharField(choices=[('heures', 'heures'), ('jours', 'jours'), ('mois', 'mois'), ('ans', 'ans'), ('trimestres', 'trimestres')], default='Jour', max_length=120, verbose_name='Unité de mesure'),
        ),
    ]
