# Generated by Django 5.1.6 on 2025-03-30 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0004_certification_duration_measure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='mastery',
        ),
    ]
